In [1]:
# Import numerical libraries
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from tableone import TableOne

ModuleNotFoundError: No module named 'tableone'

In [3]:
data = pd.read_csv('base_doencas_cardiacas.csv')

In [ ]:
categorical = ['V0001', 'V0015', 'V0026', 'V0031', 'B001', 'C006', 'C009', 'C011', 'C012', 'D00901', 'D014', 'D015', 'E006011', 
               'E008', 'E010010', 'E027', 'F001011', 'F007011', 'F008011', 'VDF001', 'F016', 'G059', 'G060', 'G062', 'G032', 
               'I00102', 'I006', 'I004', 'I00401', 'I00402', 'I00403', 'I012', 'J001', 'J00101', 'J002', 'J00402', 'J00404', 'J007', 
               'J00801', 'J01101', 'J060', 'M001', 'M00302', 'M011011', 'M011021', 'M011051', 'M011071', 'N005', 
               'N008', 'N010', 'N011', 'N012', 'N016', 'P02601', 'P027', 'P050', 'P051', 'P06701', 'P068', 'Q00201', 'Q03001', 'Q060',
               'Q06306', 'Q06506', 'Q06507', 'Q06508', 'Q06509', 'Q06601', 'Q067', 'Q068', 'Q11006', 'R034', 'R03601', 'R03607',
               'R03608', 'R03610', 'S065', 'T001', 'H003', 'H004', 'H010']

continuous = ['C00701', 'C00702', 'C00703', 'E01602', 'E01604', 'E017', 'E01802', 'E01804', 'E019', 'P00104',
           'P00404', 'P00901', 'P01001', 'P01101', 'P02001', 'P018', 'P019', 'P02002', 'P02501', 'P02602',
           'P02801', 'P029', 'P035', 'P03701', 'P03702', 'P04501', 'P04502', 'P053', 'P05401', 'P05404',
           'P05407', 'P05410', 'P05413', 'P05416', 'P05419', 'P058', 'Q064']

In [ ]:
# Crie uma Tabela 1 simples sem nenhuma variável de agrupamento
# Teste de normalidade, multimodalidade (Teste de Mergulho de Hartigan) e valores discrepantes (teste de Tukey)

mytable = TableOne(data, categorical=categorical, continuous=continuous, dip_test=False, normal_test=False, tukey_test=False, decimals=3, include_null=True)

c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[10.0 7.0 10.0 ... 'None' 5.0 5.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 2.0 1.0 ... 'None' 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 2.0 ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 2.0 ... 2.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 1.0 2.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 2.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 1.0 ... 1.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 2.0 2.0 ... 1.0 2.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 7.0 4.0 ... 2.0 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[8.0 8.0 8.0 ... 1.0 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 1.0 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\tables.py:365: RuntimeWarning: 'E01804' has all non-numeric values. Consider including it in the list of categorical variables.
  non_continuous_warning(column)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:2019: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1409: RuntimeWarning: All-NaN slice encountered
  return _nanquantile_unchecked(
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\tableone.py:583: RuntimeWarning: Mean of empty slice
  return f.format(np.nanmean(x.values), self.statistics._std(x, self._ddof))  # type: ignore

In [ ]:
# View Table 1 (note the remarks below the table)
mytable

                       Missing              Overall
n                                              1360
V0001, n (%)      21                    109 (8.015)
                  22                     93 (6.838)
                  23                    133 (9.779)
                  24                     97 (7.132)
                  25                    108 (7.941)
                  26                    124 (9.118)
                  27                     93 (6.838)
                  28                    104 (7.647)
                  29                    123 (9.044)
                  50                    114 (8.382)
                  51                     72 (5.294)
                  52                    126 (9.265)
                  53                     64 (4.706)
V0015, n (%)      1                  1360 (100.000)
V0026, n (%)      1                   1064 (78.235)
                  2                    296 (21.765)
V0031, n (%)      1                    564 (41.471)
                  2                     128 (9.412)
                  3                      10 (0.735)
                  4                    658 (48.382)
B001, n (%)       1.0                  956 (70.294)
                  2.0                  283 (20.809)
                  3.0                   121 (8.897)
C006, n (%)       1.0                  583 (42.868)
                  2.0                  777 (57.132)
C00701, mean (SD)            0      17.190 (15.451)
C00702, mean (SD)            0       8.816 (14.630)
C00703, mean (SD)            0  2148.129 (1238.560)
C009, n (%)       1.0                  453 (33.309)
                  2.0                  163 (11.985)
                  3.0                     5 (0.368)
                  4.0                  723 (53.162)
                  5.0                    16 (1.176)
C011, n (%)       1.0                  607 (44.632)
                  2.0                  163 (11.985)
                  3.0                  297 (21.838)
                  4.0                  293 (21.544)
C012, n (%)       1.0                 1082 (79.559)
                  2.0                  278 (20.441)
D00901, n (%)     1.0                     3 (0.221)
                  10.0                 175 (12.868)
                  11.0                   14 (1.029)
                  12.0                  109 (8.015)
                  13.0                   42 (3.088)
                  14.0                    8 (0.588)
                  15.0                    4 (0.294)
                  2.0                     9 (0.662)
                  3.0                    67 (4.926)
                  4.0                    25 (1.838)
                  5.0                  357 (26.250)
                  6.0                    51 (3.750)
                  7.0                  177 (13.015)
                  8.0                    27 (1.985)
                  9.0                    70 (5.147)
                  None                 222 (16.324)
D014, n (%)       1.0                  528 (38.824)
                  2.0                  548 (40.294)
                  None                 284 (20.882)
D015, n (%)       1.0                 1079 (79.338)
                  2.0                  281 (20.662)
E006011, n (%)    1.0                     2 (0.147)
                  3.0                    12 (0.882)
                  5.0                     3 (0.221)
                  7.0                     2 (0.147)
                  None                1341 (98.603)
E008, n (%)       1.0                     2 (0.147)
                  2.0                    10 (0.735)
                  None                1348 (99.118)
E010010, n (%)    2.0                     4 (0.294)
                  3.0                     1 (0.074)
                  None                1355 (99.632)
E01602, mean (SD)          965  2418.914 (4971.847)
E01604, mean (SD)         1355    650.000 (559.017)
E017, mean (SD)            959      34.903 (15.246)
E01802, mean (SD)         1332  1872.607 (3308.438)
E01804, mean (SD)         1360            nan (nan)
E019, mean (SD)           1332      17.786 (11.432)
E027, n (%)       1.0                 1072 (78.824)
                  2.0                  288 (21.176)
F001011, n (%)    1.0                  852 (62.647)
                  2.0                  508 (37.353)
F007011, n (%)    1.0                    55 (4.044)
                  2.0                 1305 (95.956)
F008011, n (%)    1.0                    87 (6.397)
                  2.0                 1273 (93.603)
VDF001, n (%)     1.0                  180 (13.235)
                  2.0                 1180 (86.765)
F016, n (%)       1.0                 1073 (78.897)
                  2.0                  287 (21.103)
G059, n (%)       1.0                   119 (8.750)
                  2.0                 1241 (91.250)
G060, n (%)       1.0                    30 (2.206)
                  2.0                    89 (6.544)
                  None                1241 (91.250)
G062, n (%)       1.0                    91 (6.691)
                  2.0                    28 (2.059)
                  None                1241 (91.250)
G032, n (%)       1.0                 1074 (78.971)
                  2.0                  286 (21.029)
I00102, n (%)     1.0                  331 (24.338)
                  2.0                 1029 (75.662)
I006, n (%)       1.0                    76 (5.588)
                  2.0                  163 (11.985)
                  3.0                    74 (5.441)
                  4.0                     9 (0.662)
                  5.0                     4 (0.294)
                  6.0                     5 (0.368)
                  None                1029 (75.662)
I004, n (%)       1.0                   114 (8.382)
                  2.0                  149 (10.956)
                  None                1097 (80.662)
I00401, n (%)     1.0                  261 (19.191)
                  2.0                     2 (0.147)
                  None                1097 (80.662)
I00402, n (%)     1.0                  261 (19.191)
                  2.0                     2 (0.147)
                  None                1097 (80.662)
I00403, n (%)     1.0                  249 (18.309)
                  2.0                    14 (1.029)
                  None                1097 (80.662)
I012, n (%)       1.0                 1076 (79.118)
                  2.0                  284 (20.882)
J001, n (%)       1.0                    41 (3.015)
                  2.0                  296 (21.765)
                  3.0                  691 (50.809)
                  4.0                  255 (18.750)
                  5.0                    77 (5.662)
J00101, n (%)     1.0                    90 (6.618)
                  2.0                  529 (38.897)
                  3.0                  530 (38.971)
                  4.0                  166 (12.206)
                  5.0                    45 (3.309)
J002, n (%)       1.0                  295 (21.691)
                  2.0                 1065 (78.309)
J00402, n (%)     1.0                   104 (7.647)
                  10.0                    6 (0.441)
                  11.0                    4 (0.294)
                  12.0                   15 (1.103)
                  13.0                   13 (0.956)
                  14.0                   18 (1.324)
                  2.0                    13 (0.956)
                  3.0                     1 (0.074)
                  5.0                    22 (1.618)
                  6.0                    10 (0.735)
                  7.0                     5 (0.368)
                  8.0                    75 (5.515)
                  9.0                     9 (0.662)
                  None                1065 (78.309)
J00404, n (%)     1.0                    22 (1.618)
                  2.0                  230 (16.912)
                  3.0                    43 (3.162)
                  None                1065 (78.309)
J007, n (%)       1.0                1360 (100.000)
J00801, n (%)     1.0                 1079 (79.338)
                  2.0                  281 (20.662)
J01101, n (%)     1.0                 1289 (94.779)
                  2.0                    46 (3.382)
                  3.0                    11 (0.809)
                  4.0                    14 (1.029)
J060, n (%)       1.0                 1082 (79.559)
                  2.0                  278 (20.441)
M001, n (%)       1.0                1360 (100.000)
M00302, n (%)     1.0                    57 (4.191)
                  None                1303 (95.809)
M011011, n (%)    1.0                    29 (2.132)
                  2.0                  372 (27.353)
                  None                 959 (70.515)
M011021, n (%)    1.0                    65 (4.779)
                  2.0                  336 (24.706)
                  None                 959 (70.515)
M011051, n (%)    1.0                    22 (1.618)
                  2.0                  379 (27.868)
                  None                 959 (70.515)
M011071, n (%)    1.0                    35 (2.574)
                  2.0                  366 (26.912)
                  None                 959 (70.515)
N005, n (%)       1.0                  243 (17.868)
                  2.0                  998 (73.382)
                  None                  119 (8.750)
N008, n (%)       1.0                  402 (29.559)
                  2.0                    61 (4.485)
                  3.0                    42 (3.088)
                  4.0                    11 (0.809)
                  None                 844 (62.059)
N010, n (%)       1.0                  576 (42.353)
                  2.0                  298 (21.912)
                  3.0                  168 (12.353)
                  4.0                  318 (23.382)
N011, n (%)       1.0                  627 (46.103)
                  2.0                  394 (28.971)
                  3.0                  155 (11.397)
                  4.0                  184 (13.529)
N012, n (%)       1.0                  779 (57.279)
                  2.0                  330 (24.265)
                  3.0                   121 (8.897)
                  4.0                   130 (9.559)
N016, n (%)       1.0                  797 (58.603)
                  2.0                  308 (22.647)
                  3.0                   113 (8.309)
                  4.0                  142 (10.441)
P00104, mean (SD)            0      71.118 (14.691)
P00404, mean (SD)            0      162.235 (9.095)
P00901, mean (SD)            0        4.460 (2.506)
P01001, mean (SD)          634        1.271 (0.478)
P01101, mean (SD)            0        2.963 (2.183)
P02001, mean (SD)            0        0.637 (1.616)
P018, mean (SD)              0        4.685 (2.475)
P019, mean (SD)            593        1.563 (0.696)
P02002, mean (SD)            0        0.543 (1.314)
P02501, mean (SD)            0        1.176 (1.959)
P02602, mean (SD)            0        0.190 (0.826)
P02601, n (%)     1.0                     8 (0.588)
                  2.0                    84 (6.176)
                  3.0                  568 (41.765)
                  4.0                  564 (41.471)
                  5.0                  136 (10.000)
P027, n (%)       1.0                 1085 (79.779)
                  2.0                   102 (7.500)
                  3.0                  173 (12.721)
P02801, mean (SD)         1187        2.214 (1.978)
P029, mean (SD)           1085        3.713 (3.220)
P035, mean (SD)            939        3.774 (1.895)
P03701, mean (SD)          949        0.625 (0.674)
P03702, mean (SD)          949      18.491 (17.073)
P04501, mean (SD)            0        3.176 (1.501)
P04502, mean (SD)            0        4.390 (2.062)
P050, n (%)       1.0                   119 (8.750)
                  2.0                     7 (0.515)
                  3.0                 1234 (90.735)
P051, n (%)       1.0                     4 (0.294)
                  2.0                     3 (0.221)
                  None                1353 (99.485)
P053, mean (SD)            679       16.225 (7.015)
P05401, mean (SD)         1234        2.516 (1.892)
P05404, mean (SD)         1234        3.484 (1.892)
P05407, mean (SD)         1234        4.984 (0.178)
P05410, mean (SD)         1234        4.802 (0.839)
P05413, mean (SD)         1234        4.952 (0.397)
P05416, mean (SD)         1234        5.000 (0.000)
P05419, mean (SD)         1234        4.968 (0.356)
P058, mean (SD)            742        1.992 (1.718)
P06701, n (%)     1.0                     1 (0.074)
                  3.0                     2 (0.147)
                  4.0                 1357 (99.779)
P068, n (%)       1.0                  170 (12.500)
                  2.0                    24 (1.765)
                  3.0                     6 (0.441)
                  4.0                    22 (1.618)
                  5.0                 1138 (83.676)
Q00201, n (%)     1.0                  965 (70.956)
                  2.0                  394 (28.971)
                  None                    1 (0.074)
Q03001, n (%)     1.0                  349 (25.662)
                  2.0                 1001 (73.603)
                  None                   10 (0.735)
Q060, n (%)       1.0                  597 (43.897)
                  2.0                  747 (54.926)
                  None                   16 (1.176)
Q06306, n (%)     1.0                1360 (100.000)
Q064, mean (SD)              0      57.510 (11.548)
Q06506, n (%)     1.0                  746 (54.853)
                  2.0                  614 (45.147)
Q06507, n (%)     1.0                  444 (32.647)
                  2.0                  916 (67.353)
Q06508, n (%)     1.0                 1062 (78.088)
                  2.0                  298 (21.912)
Q06509, n (%)     1.0                  955 (70.221)
                  2.0                  405 (29.779)
Q06601, n (%)     1.0                  468 (34.412)
                  2.0                  892 (65.588)
Q067, n (%)       1.0                  632 (46.471)
                  2.0                  347 (25.515)
                  3.0                  216 (15.882)
                  4.0                   125 (9.191)
                  5.0                    40 (2.941)
Q068, n (%)       1.0                  161 (11.838)
                  2.0                 1199 (88.162)
Q11006, n (%)     1.0                   109 (8.015)
                  2.0                 1251 (91.985)
R034, n (%)       1.0                    15 (1.103)
                  2.0                    26 (1.912)
                  None                1319 (96.985)
R03601, n (%)     1.0                     5 (0.368)
                  2.0                    10 (0.735)
                  None                1345 (98.897)
R03607, n (%)     1.0                     1 (0.074)
                  2.0                    14 (1.029)
                  None                1345 (98.897)
R03608, n (%)     2.0                    15 (1.103)
                  None                1345 (98.897)
R03610, n (%)     2.0                    15 (1.103)
                  None                1345 (98.897)
S065, n (%)       1.0                  703 (51.691)
                  2.0                    74 (5.441)
                  None                 583 (42.868)
T001, n (%)       1.0                    90 (6.618)
                  2.0                 1270 (93.382)
H003, n (%)       1.0                     7 (0.515)
                  2.0                  283 (20.809)
                  4.0                  265 (19.485)
                  5.0                     6 (0.441)
                  6.0                     6 (0.441)
                  7.0                  137 (10.074)
                  None                 656 (48.235)
H004, n (%)       1.0                  219 (16.103)
                  10.0                    9 (0.662)
                  11.0                    3 (0.221)
                  12.0                   13 (0.956)
                  13.0                    2 (0.147)
                  2.0                    29 (2.132)
                  3.0                     2 (0.147)
                  4.0                    16 (1.176)
                  5.0                     3 (0.221)
                  6.0                     9 (0.662)
                  7.0                    92 (6.765)
                  8.0                  305 (22.426)
                  9.0                     2 (0.147)
                  None                 656 (48.235)
H010, n (%)       1.0                    72 (5.294)
                  2.0                    39 (2.868)
                  3.0                    42 (3.088)
                  4.0                    65 (4.779)
                  5.0                     1 (0.074)
                  None                1141 (83.897)

In [ ]:
print(mytable.tabulate(tablefmt="github"))

|                   |      | Missing   | Overall             |
|-------------------|------|-----------|---------------------|
| n                 |      |           | 1360                |
| V0001, n (%)      | 21   |           | 109 (8.015)         |
|                   | 22   |           | 93 (6.838)          |
|                   | 23   |           | 133 (9.779)         |
|                   | 24   |           | 97 (7.132)          |
|                   | 25   |           | 108 (7.941)         |
|                   | 26   |           | 124 (9.118)         |
|                   | 27   |           | 93 (6.838)          |
|                   | 28   |           | 104 (7.647)         |
|                   | 29   |           | 123 (9.044)         |
|                   | 50   |           | 114 (8.382)         |
|                   | 51   |           | 72 (5.294)          |
|                   | 52   |           | 126 (9.265)         |
|                   | 53   |           | 64 (4.706)          |
| V0015, n (%)      | 1    |           | 1360 (100.000)      |
| V0026, n (%)      | 1    |           | 1064 (78.235)       |
|                   | 2    |           | 296 (21.765)        |
| V0031, n (%)      | 1    |           | 564 (41.471)        |
|                   | 2    |           | 128 (9.412)         |
|                   | 3    |           | 10 (0.735)          |
|                   | 4    |           | 658 (48.382)        |
| B001, n (%)       | 1.0  |           | 956 (70.294)        |
|                   | 2.0  |           | 283 (20.809)        |
|                   | 3.0  |           | 121 (8.897)         |
| C006, n (%)       | 1.0  |           | 583 (42.868)        |
|                   | 2.0  |           | 777 (57.132)        |
| C00701, mean (SD) |      | 0         | 17.190 (15.451)     |
| C00702, mean (SD) |      | 0         | 8.816 (14.630)      |
| C00703, mean (SD) |      | 0         | 2148.129 (1238.560) |
| C009, n (%)       | 1.0  |           | 453 (33.309)        |
|                   | 2.0  |           | 163 (11.985)        |
|                   | 3.0  |           | 5 (0.368)           |
|                   | 4.0  |           | 723 (53.162)        |
|                   | 5.0  |           | 16 (1.176)          |
| C011, n (%)       | 1.0  |           | 607 (44.632)        |
|                   | 2.0  |           | 163 (11.985)        |
|                   | 3.0  |           | 297 (21.838)        |
|                   | 4.0  |           | 293 (21.544)        |
| C012, n (%)       | 1.0  |           | 1082 (79.559)       |
|                   | 2.0  |           | 278 (20.441)        |
| D00901, n (%)     | 1.0  |           | 3 (0.221)           |
|                   | 10.0 |           | 175 (12.868)        |
|                   | 11.0 |           | 14 (1.029)          |
|                   | 12.0 |           | 109 (8.015)         |
|                   | 13.0 |           | 42 (3.088)          |
|                   | 14.0 |           | 8 (0.588)           |
|                   | 15.0 |           | 4 (0.294)           |
|                   | 2.0  |           | 9 (0.662)           |
|                   | 3.0  |           | 67 (4.926)          |
|                   | 4.0  |           | 25 (1.838)          |
|                   | 5.0  |           | 357 (26.250)        |
|                   | 6.0  |           | 51 (3.750)          |
|                   | 7.0  |           | 177 (13.015)        |
|                   | 8.0  |           | 27 (1.985)          |
|                   | 9.0  |           | 70 (5.147)          |
|                   | None |           | 222 (16.324)        |
| D014, n (%)       | 1.0  |           | 528 (38.824)        |
|                   | 2.0  |           | 548 (40.294)        |
|                   | None |           | 284 (20.882)        |
| D015, n (%)       | 1.0  |           | 1079 (79.338)       |
|                   | 2.0  |           | 281 (20.662)        |
| E006011, n (%)    | 1.0  |           | 2 (0.147)           |
|                   | 3.0  |           | 12 (0.882)          |
|                   | 5.0  |           | 3 (0.221)           |
|                   | 7.0  |           | 2 (0.147)           |
|                   | None |           | 1341 (98.603)       |
| E008, n (%)       | 1.0  |           | 2 (0.147)           |
|                   | 2.0  |           | 10 (0.735)          |
|                   | None |           | 1348 (99.118)       |
| E010010, n (%)    | 2.0  |           | 4 (0.294)           |
|                   | 3.0  |           | 1 (0.074)           |
|                   | None |           | 1355 (99.632)       |
| E01602, mean (SD) |      | 965       | 2418.914 (4971.847) |
| E01604, mean (SD) |      | 1355      | 650.000 (559.017)   |
| E017, mean (SD)   |      | 959       | 34.903 (15.246)     |
| E01802, mean (SD) |      | 1332      | 1872.607 (3308.438) |
| E01804, mean (SD) |      | 1360      | nan (nan)           |
| E019, mean (SD)   |      | 1332      | 17.786 (11.432)     |
| E027, n (%)       | 1.0  |           | 1072 (78.824)       |
|                   | 2.0  |           | 288 (21.176)        |
| F001011, n (%)    | 1.0  |           | 852 (62.647)        |
|                   | 2.0  |           | 508 (37.353)        |
| F007011, n (%)    | 1.0  |           | 55 (4.044)          |
|                   | 2.0  |           | 1305 (95.956)       |
| F008011, n (%)    | 1.0  |           | 87 (6.397)          |
|                   | 2.0  |           | 1273 (93.603)       |
| VDF001, n (%)     | 1.0  |           | 180 (13.235)        |
|                   | 2.0  |           | 1180 (86.765)       |
| F016, n (%)       | 1.0  |           | 1073 (78.897)       |
|                   | 2.0  |           | 287 (21.103)        |
| G059, n (%)       | 1.0  |           | 119 (8.750)         |
|                   | 2.0  |           | 1241 (91.250)       |
| G060, n (%)       | 1.0  |           | 30 (2.206)          |
|                   | 2.0  |           | 89 (6.544)          |
|                   | None |           | 1241 (91.250)       |
| G062, n (%)       | 1.0  |           | 91 (6.691)          |
|                   | 2.0  |           | 28 (2.059)          |
|                   | None |           | 1241 (91.250)       |
| G032, n (%)       | 1.0  |           | 1074 (78.971)       |
|                   | 2.0  |           | 286 (21.029)        |
| I00102, n (%)     | 1.0  |           | 331 (24.338)        |
|                   | 2.0  |           | 1029 (75.662)       |
| I006, n (%)       | 1.0  |           | 76 (5.588)          |
|                   | 2.0  |           | 163 (11.985)        |
|                   | 3.0  |           | 74 (5.441)          |
|                   | 4.0  |           | 9 (0.662)           |
|                   | 5.0  |           | 4 (0.294)           |
|                   | 6.0  |           | 5 (0.368)           |
|                   | None |           | 1029 (75.662)       |
| I004, n (%)       | 1.0  |           | 114 (8.382)         |
|                   | 2.0  |           | 149 (10.956)        |
|                   | None |           | 1097 (80.662)       |
| I00401, n (%)     | 1.0  |           | 261 (19.191)        |
|                   | 2.0  |           | 2 (0.147)           |
|                   | None |           | 1097 (80.662)       |
| I00402, n (%)     | 1.0  |           | 261 (19.191)        |
|                   | 2.0  |           | 2 (0.147)           |
|                   | None |           | 1097 (80.662)       |
| I00403, n (%)     | 1.0  |           | 249 (18.309)        |
|                   | 2.0  |           | 14 (1.029)          |
|                   | None |           | 1097 (80.662)       |
| I012, n (%)       | 1.0  |           | 1076 (79.118)       |
|                   | 2.0  |           | 284 (20.882)        |
| J001, n (%)       | 1.0  |           | 41 (3.015)          |
|                   | 2.0  |           | 296 (21.765)        |
|                   | 3.0  |           | 691 (50.809)        |
|                   | 4.0  |           | 255 (18.750)        |
|                   | 5.0  |           | 77 (5.662)          |
| J00101, n (%)     | 1.0  |           | 90 (6.618)          |
|                   | 2.0  |           | 529 (38.897)        |
|                   | 3.0  |           | 530 (38.971)        |
|                   | 4.0  |           | 166 (12.206)        |
|                   | 5.0  |           | 45 (3.309)          |
| J002, n (%)       | 1.0  |           | 295 (21.691)        |
|                   | 2.0  |           | 1065 (78.309)       |
| J00402, n (%)     | 1.0  |           | 104 (7.647)         |
|                   | 10.0 |           | 6 (0.441)           |
|                   | 11.0 |           | 4 (0.294)           |
|                   | 12.0 |           | 15 (1.103)          |
|                   | 13.0 |           | 13 (0.956)          |
|                   | 14.0 |           | 18 (1.324)          |
|                   | 2.0  |           | 13 (0.956)          |
|                   | 3.0  |           | 1 (0.074)           |
|                   | 5.0  |           | 22 (1.618)          |
|                   | 6.0  |           | 10 (0.735)          |
|                   | 7.0  |           | 5 (0.368)           |
|                   | 8.0  |           | 75 (5.515)          |
|                   | 9.0  |           | 9 (0.662)           |
|                   | None |           | 1065 (78.309)       |
| J00404, n (%)     | 1.0  |           | 22 (1.618)          |
|                   | 2.0  |           | 230 (16.912)        |
|                   | 3.0  |           | 43 (3.162)          |
|                   | None |           | 1065 (78.309)       |
| J007, n (%)       | 1.0  |           | 1360 (100.000)      |
| J00801, n (%)     | 1.0  |           | 1079 (79.338)       |
|                   | 2.0  |           | 281 (20.662)        |
| J01101, n (%)     | 1.0  |           | 1289 (94.779)       |
|                   | 2.0  |           | 46 (3.382)          |
|                   | 3.0  |           | 11 (0.809)          |
|                   | 4.0  |           | 14 (1.029)          |
| J060, n (%)       | 1.0  |           | 1082 (79.559)       |
|                   | 2.0  |           | 278 (20.441)        |
| M001, n (%)       | 1.0  |           | 1360 (100.000)      |
| M00302, n (%)     | 1.0  |           | 57 (4.191)          |
|                   | None |           | 1303 (95.809)       |
| M011011, n (%)    | 1.0  |           | 29 (2.132)          |
|                   | 2.0  |           | 372 (27.353)        |
|                   | None |           | 959 (70.515)        |
| M011021, n (%)    | 1.0  |           | 65 (4.779)          |
|                   | 2.0  |           | 336 (24.706)        |
|                   | None |           | 959 (70.515)        |
| M011051, n (%)    | 1.0  |           | 22 (1.618)          |
|                   | 2.0  |           | 379 (27.868)        |
|                   | None |           | 959 (70.515)        |
| M011071, n (%)    | 1.0  |           | 35 (2.574)          |
|                   | 2.0  |           | 366 (26.912)        |
|                   | None |           | 959 (70.515)        |
| N005, n (%)       | 1.0  |           | 243 (17.868)        |
|                   | 2.0  |           | 998 (73.382)        |
|                   | None |           | 119 (8.750)         |
| N008, n (%)       | 1.0  |           | 402 (29.559)        |
|                   | 2.0  |           | 61 (4.485)          |
|                   | 3.0  |           | 42 (3.088)          |
|                   | 4.0  |           | 11 (0.809)          |
|                   | None |           | 844 (62.059)        |
| N010, n (%)       | 1.0  |           | 576 (42.353)        |
|                   | 2.0  |           | 298 (21.912)        |
|                   | 3.0  |           | 168 (12.353)        |
|                   | 4.0  |           | 318 (23.382)        |
| N011, n (%)       | 1.0  |           | 627 (46.103)        |
|                   | 2.0  |           | 394 (28.971)        |
|                   | 3.0  |           | 155 (11.397)        |
|                   | 4.0  |           | 184 (13.529)        |
| N012, n (%)       | 1.0  |           | 779 (57.279)        |
|                   | 2.0  |           | 330 (24.265)        |
|                   | 3.0  |           | 121 (8.897)         |
|                   | 4.0  |           | 130 (9.559)         |
| N016, n (%)       | 1.0  |           | 797 (58.603)        |
|                   | 2.0  |           | 308 (22.647)        |
|                   | 3.0  |           | 113 (8.309)         |
|                   | 4.0  |           | 142 (10.441)        |
| P00104, mean (SD) |      | 0         | 71.118 (14.691)     |
| P00404, mean (SD) |      | 0         | 162.235 (9.095)     |
| P00901, mean (SD) |      | 0         | 4.460 (2.506)       |
| P01001, mean (SD) |      | 634       | 1.271 (0.478)       |
| P01101, mean (SD) |      | 0         | 2.963 (2.183)       |
| P02001, mean (SD) |      | 0         | 0.637 (1.616)       |
| P018, mean (SD)   |      | 0         | 4.685 (2.475)       |
| P019, mean (SD)   |      | 593       | 1.563 (0.696)       |
| P02002, mean (SD) |      | 0         | 0.543 (1.314)       |
| P02501, mean (SD) |      | 0         | 1.176 (1.959)       |
| P02602, mean (SD) |      | 0         | 0.190 (0.826)       |
| P02601, n (%)     | 1.0  |           | 8 (0.588)           |
|                   | 2.0  |           | 84 (6.176)          |
|                   | 3.0  |           | 568 (41.765)        |
|                   | 4.0  |           | 564 (41.471)        |
|                   | 5.0  |           | 136 (10.000)        |
| P027, n (%)       | 1.0  |           | 1085 (79.779)       |
|                   | 2.0  |           | 102 (7.500)         |
|                   | 3.0  |           | 173 (12.721)        |
| P02801, mean (SD) |      | 1187      | 2.214 (1.978)       |
| P029, mean (SD)   |      | 1085      | 3.713 (3.220)       |
| P035, mean (SD)   |      | 939       | 3.774 (1.895)       |
| P03701, mean (SD) |      | 949       | 0.625 (0.674)       |
| P03702, mean (SD) |      | 949       | 18.491 (17.073)     |
| P04501, mean (SD) |      | 0         | 3.176 (1.501)       |
| P04502, mean (SD) |      | 0         | 4.390 (2.062)       |
| P050, n (%)       | 1.0  |           | 119 (8.750)         |
|                   | 2.0  |           | 7 (0.515)           |
|                   | 3.0  |           | 1234 (90.735)       |
| P051, n (%)       | 1.0  |           | 4 (0.294)           |
|                   | 2.0  |           | 3 (0.221)           |
|                   | None |           | 1353 (99.485)       |
| P053, mean (SD)   |      | 679       | 16.225 (7.015)      |
| P05401, mean (SD) |      | 1234      | 2.516 (1.892)       |
| P05404, mean (SD) |      | 1234      | 3.484 (1.892)       |
| P05407, mean (SD) |      | 1234      | 4.984 (0.178)       |
| P05410, mean (SD) |      | 1234      | 4.802 (0.839)       |
| P05413, mean (SD) |      | 1234      | 4.952 (0.397)       |
| P05416, mean (SD) |      | 1234      | 5.000 (0.000)       |
| P05419, mean (SD) |      | 1234      | 4.968 (0.356)       |
| P058, mean (SD)   |      | 742       | 1.992 (1.718)       |
| P06701, n (%)     | 1.0  |           | 1 (0.074)           |
|                   | 3.0  |           | 2 (0.147)           |
|                   | 4.0  |           | 1357 (99.779)       |
| P068, n (%)       | 1.0  |           | 170 (12.500)        |
|                   | 2.0  |           | 24 (1.765)          |
|                   | 3.0  |           | 6 (0.441)           |
|                   | 4.0  |           | 22 (1.618)          |
|                   | 5.0  |           | 1138 (83.676)       |
| Q00201, n (%)     | 1.0  |           | 965 (70.956)        |
|                   | 2.0  |           | 394 (28.971)        |
|                   | None |           | 1 (0.074)           |
| Q03001, n (%)     | 1.0  |           | 349 (25.662)        |
|                   | 2.0  |           | 1001 (73.603)       |
|                   | None |           | 10 (0.735)          |
| Q060, n (%)       | 1.0  |           | 597 (43.897)        |
|                   | 2.0  |           | 747 (54.926)        |
|                   | None |           | 16 (1.176)          |
| Q06306, n (%)     | 1.0  |           | 1360 (100.000)      |
| Q064, mean (SD)   |      | 0         | 57.510 (11.548)     |
| Q06506, n (%)     | 1.0  |           | 746 (54.853)        |
|                   | 2.0  |           | 614 (45.147)        |
| Q06507, n (%)     | 1.0  |           | 444 (32.647)        |
|                   | 2.0  |           | 916 (67.353)        |
| Q06508, n (%)     | 1.0  |           | 1062 (78.088)       |
|                   | 2.0  |           | 298 (21.912)        |
| Q06509, n (%)     | 1.0  |           | 955 (70.221)        |
|                   | 2.0  |           | 405 (29.779)        |
| Q06601, n (%)     | 1.0  |           | 468 (34.412)        |
|                   | 2.0  |           | 892 (65.588)        |
| Q067, n (%)       | 1.0  |           | 632 (46.471)        |
|                   | 2.0  |           | 347 (25.515)        |
|                   | 3.0  |           | 216 (15.882)        |
|                   | 4.0  |           | 125 (9.191)         |
|                   | 5.0  |           | 40 (2.941)          |
| Q068, n (%)       | 1.0  |           | 161 (11.838)        |
|                   | 2.0  |           | 1199 (88.162)       |
| Q11006, n (%)     | 1.0  |           | 109 (8.015)         |
|                   | 2.0  |           | 1251 (91.985)       |
| R034, n (%)       | 1.0  |           | 15 (1.103)          |
|                   | 2.0  |           | 26 (1.912)          |
|                   | None |           | 1319 (96.985)       |
| R03601, n (%)     | 1.0  |           | 5 (0.368)           |
|                   | 2.0  |           | 10 (0.735)          |
|                   | None |           | 1345 (98.897)       |
| R03607, n (%)     | 1.0  |           | 1 (0.074)           |
|                   | 2.0  |           | 14 (1.029)          |
|                   | None |           | 1345 (98.897)       |
| R03608, n (%)     | 2.0  |           | 15 (1.103)          |
|                   | None |           | 1345 (98.897)       |
| R03610, n (%)     | 2.0  |           | 15 (1.103)          |
|                   | None |           | 1345 (98.897)       |
| S065, n (%)       | 1.0  |           | 703 (51.691)        |
|                   | 2.0  |           | 74 (5.441)          |
|                   | None |           | 583 (42.868)        |
| T001, n (%)       | 1.0  |           | 90 (6.618)          |
|                   | 2.0  |           | 1270 (93.382)       |
| H003, n (%)       | 1.0  |           | 7 (0.515)           |
|                   | 2.0  |           | 283 (20.809)        |
|                   | 4.0  |           | 265 (19.485)        |
|                   | 5.0  |           | 6 (0.441)           |
|                   | 6.0  |           | 6 (0.441)           |
|                   | 7.0  |           | 137 (10.074)        |
|                   | None |           | 656 (48.235)        |
| H004, n (%)       | 1.0  |           | 219 (16.103)        |
|                   | 10.0 |           | 9 (0.662)           |
|                   | 11.0 |           | 3 (0.221)           |
|                   | 12.0 |           | 13 (0.956)          |
|                   | 13.0 |           | 2 (0.147)           |
|                   | 2.0  |           | 29 (2.132)          |
|                   | 3.0  |           | 2 (0.147)           |
|                   | 4.0  |           | 16 (1.176)          |
|                   | 5.0  |           | 3 (0.221)           |
|                   | 6.0  |           | 9 (0.662)           |

In [ ]:
#tem que acrescentar mínimo e máximo eu não sei fazer isso ainda
for i in continuous:
    print("{i}, mean (SD / min / max) {l}")