In [36]:
# Import numerical libraries
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
from tableone import TableOne

In [38]:
data = pd.read_csv('..\\Bases\\Criados\\3_base_doencas_cardiacas.csv')

In [39]:
categorical = ['V0001', 'V0026', 'V0031', 'B001', 'C006', 'C009', 'C011', 'D00901', 'D014',
                'F001011', 'F007011', 'F008011', 'VDF001', 'G059', 'G060', 'G062', 
                'I00102', 'I006', 'I004', 'I00401', 'I00402', 'I00403', 'J001', 'J00101', 'J01101', 
                'M00203', 'M011011', 'M011021', 'M011051', 'M011071', 'N004', 'N005', 'N008', 'N010', 'N011', 'N012', 'N016', 'P02601', 'P027',
                'P04501', 'P04502', 'P050', 'P051', 'P052', 'P05401', 'P05404', 'P05407', 'P05410', 'P05413', 'P05416', 'P05419', 'P06701', 'P068', 
                'Q00201', 'Q03001', 'Q060', 'Q06306', 'Q068', 'Q11006', 'Q128', 'R034', 'T001', 'H003', 'H004', 'H010',
                'D00201', 'D00301', 'D008', 'E011', 'E014011', 'E01601', 'E01801', 'I00103', 'I001031', 'P034', 'Q00101', 'Q02901', 'Q05901'] #adicionados para análise

continuous = ['C008', 'E01602', 'E017', 'E01802', 'E019', 'F001021', 'F007021', 'F008021', 'VDF00102', 'P00104', 'P00404', 'P00901', 
              'P01101', 'P02001', 'P018', 'P02002', 'P02501', 'P02602', 'P02801', 'P029', 'P035', 'P03701', 'P03702', 'P053',
              'P00103', 'P00403', 'P05901', 'P05902', 'P05903', 'P05904'] #adicionados para análise


'''
Colunas pra adicionar: 

'H001', 'H002',
'''

"\nColunas pra adicionar: \n\n'H001', 'H002',\n"

In [40]:
# Crie uma Tabela 1 simples sem nenhuma variável de agrupamento
# Teste de normalidade, multimodalidade (Teste de Mergulho de Hartigan) e valores discrepantes (teste de Tukey)

mytable = TableOne(data, categorical=categorical, continuous=continuous, dip_test=False, normal_test=False, tukey_test=False, decimals=3, include_null=True)

c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[10.0 10.0 13.0 ... 10.0 10.0 11.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 3.0 3.0 ... 'None' 'None' 4.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 1.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.0 2.0 1.0 ... 'None' 'None' 3.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 1.0 1.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 5.0 5.0 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 2.0 ... 2.0 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 4.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 8.0 8.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 1.0 ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 1.0 ... 'None' 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)

In [41]:
print(mytable.tabulate(tablefmt="github"))

|                     |      | Missing   | Overall             |
|---------------------|------|-----------|---------------------|
| n                   |      |           | 20528               |
| V0001, n (%)        | 21   |           | 2238 (10.902)       |
|                     | 22   |           | 1345 (6.552)        |
|                     | 23   |           | 1990 (9.694)        |
|                     | 24   |           | 1416 (6.898)        |
|                     | 25   |           | 1548 (7.541)        |
|                     | 26   |           | 2013 (9.806)        |
|                     | 27   |           | 1465 (7.137)        |
|                     | 28   |           | 1328 (6.469)        |
|                     | 29   |           | 1875 (9.134)        |
|                     | 50   |           | 1466 (7.141)        |
|                     | 51   |           | 1255 (6.114)        |
|                     | 52   |           | 1454 (7.083)        |
|                     | 53   |           | 1135 (5.529)        |
| V0026, n (%)        | 1    |           | 15158 (73.841)      |
|                     | 2    |           | 5370 (26.159)       |
| V0031, n (%)        | 1    |           | 7609 (37.066)       |
|                     | 2    |           | 2361 (11.501)       |
|                     | 3    |           | 281 (1.369)         |
|                     | 4    |           | 10277 (50.063)      |
| B001, n (%)         | 1.0  |           | 13975 (68.078)      |
|                     | 2.0  |           | 4394 (21.405)       |
|                     | 3.0  |           | 2159 (10.517)       |
| C006, n (%)         | 1.0  |           | 9454 (46.054)       |
|                     | 2.0  |           | 11074 (53.946)      |
| C008, mean (SD)     |      | 0         | 53.537 (8.644)      |
| C009, n (%)         | 1.0  |           | 5933 (28.902)       |
|                     | 2.0  |           | 2619 (12.758)       |
|                     | 3.0  |           | 134 (0.653)         |
|                     | 4.0  |           | 11677 (56.883)      |
|                     | 5.0  |           | 163 (0.794)         |
|                     | 9.0  |           | 2 (0.010)           |
| C011, n (%)         | 1.0  |           | 9301 (45.309)       |
|                     | 2.0  |           | 2324 (11.321)       |
|                     | 3.0  |           | 1690 (8.233)        |
|                     | 4.0  |           | 7213 (35.137)       |
| D00901, n (%)       | 1.0  |           | 4 (0.019)           |
|                     | 10.0 |           | 4352 (21.200)       |
|                     | 11.0 |           | 279 (1.359)         |
|                     | 12.0 |           | 1956 (9.528)        |
|                     | 13.0 |           | 739 (3.600)         |
|                     | 14.0 |           | 123 (0.599)         |
|                     | 15.0 |           | 50 (0.244)          |
|                     | 2.0  |           | 105 (0.511)         |
|                     | 3.0  |           | 796 (3.878)         |
|                     | 4.0  |           | 238 (1.159)         |
|                     | 5.0  |           | 2768 (13.484)       |
|                     | 6.0  |           | 520 (2.533)         |
|                     | 7.0  |           | 5444 (26.520)       |
|                     | 8.0  |           | 394 (1.919)         |
|                     | 9.0  |           | 371 (1.807)         |
|                     | None |           | 2389 (11.638)       |
| D014, n (%)         | 1.0  |           | 8691 (42.337)       |
|                     | 2.0  |           | 8658 (42.177)       |
|                     | None |           | 3179 (15.486)       |
| E01602, mean (SD)   |      | 8803      | 2111.872 (3646.778) |
| E017, mean (SD)     |      | 8593      | 36.427 (13.816)     |
| E01802, mean (SD)   |      | 19821     | 1638.209 (2421.549) |
| E019, mean (SD)     |      | 19804     | 18.028 (10.907)     |
| F001011, n (%)      | 1.0  |           | 5768 (28.098)       |
|                     | 2.0  |           | 14760 (71.902)      |
| F001021, mean (SD)  |      | 14760     | 1814.454 (2302.341) |
| F007011, n (%)      | 1.0  |           | 651 (3.171)         |
|                     | 2.0  |           | 19877 (96.829)      |
| F007021, mean (SD)  |      | 19877     | 752.610 (1173.216)  |
| F008011, n (%)      | 1.0  |           | 954 (4.647)         |
|                     | 2.0  |           | 19574 (95.353)      |
| F008021, mean (SD)  |      | 19574     | 1342.083 (4695.524) |
| VDF001, n (%)       | 1.0  |           | 3109 (15.145)       |
|                     | 2.0  |           | 17419 (84.855)      |
| VDF00102, mean (SD) |      | 17419     | 575.894 (7598.370)  |
| G059, n (%)         | 1.0  |           | 348 (1.695)         |
|                     | 2.0  |           | 20180 (98.305)      |
| G060, n (%)         | 1.0  |           | 75 (0.365)          |
|                     | 2.0  |           | 273 (1.330)         |
|                     | None |           | 20180 (98.305)      |
| G062, n (%)         | 1.0  |           | 264 (1.286)         |
|                     | 2.0  |           | 84 (0.409)          |
|                     | None |           | 20180 (98.305)      |
| I00102, n (%)       | 1.0  |           | 3842 (18.716)       |
|                     | 2.0  |           | 16686 (81.284)      |
| I006, n (%)         | 1.0  |           | 839 (4.087)         |
|                     | 2.0  |           | 1983 (9.660)        |
|                     | 3.0  |           | 795 (3.873)         |
|                     | 4.0  |           | 97 (0.473)          |
|                     | 5.0  |           | 44 (0.214)          |
|                     | 6.0  |           | 84 (0.409)          |
|                     | None |           | 16686 (81.284)      |
| I004, n (%)         | 1.0  |           | 1059 (5.159)        |
|                     | 2.0  |           | 1814 (8.837)        |
|                     | None |           | 17655 (86.004)      |
| I00401, n (%)       | 1.0  |           | 2839 (13.830)       |
|                     | 2.0  |           | 34 (0.166)          |
|                     | None |           | 17655 (86.004)      |
| I00402, n (%)       | 1.0  |           | 2823 (13.752)       |
|                     | 2.0  |           | 50 (0.244)          |
|                     | None |           | 17655 (86.004)      |
| I00403, n (%)       | 1.0  |           | 2703 (13.167)       |
|                     | 2.0  |           | 170 (0.828)         |
|                     | None |           | 17655 (86.004)      |
| J001, n (%)         | 1.0  |           | 1766 (8.603)        |
|                     | 2.0  |           | 8711 (42.435)       |
|                     | 3.0  |           | 7964 (38.796)       |
|                     | 4.0  |           | 1692 (8.242)        |
|                     | 5.0  |           | 395 (1.924)         |
| J00101, n (%)       | 1.0  |           | 2385 (11.618)       |
|                     | 2.0  |           | 11328 (55.183)      |
|                     | 3.0  |           | 5518 (26.880)       |
|                     | 4.0  |           | 1099 (5.354)        |
|                     | 5.0  |           | 198 (0.965)         |
| J01101, n (%)       | 1.0  |           | 16319 (79.496)      |
|                     | 2.0  |           | 1955 (9.524)        |
|                     | 3.0  |           | 666 (3.244)         |
|                     | 4.0  |           | 1451 (7.068)        |
|                     | 5.0  |           | 137 (0.667)         |
| M00203, n (%)       | 1.0  |           | 20333 (99.050)      |
|                     | 2.0  |           | 190 (0.926)         |
|                     | 9.0  |           | 3 (0.015)           |
|                     | None |           | 2 (0.010)           |
| M011011, n (%)      | 1.0  |           | 1372 (6.684)        |
|                     | 2.0  |           | 10563 (51.457)      |
|                     | None |           | 8593 (41.860)       |
| M011021, n (%)      | 1.0  |           | 2213 (10.780)       |
|                     | 2.0  |           | 9722 (47.360)       |
|                     | None |           | 8593 (41.860)       |
| M011051, n (%)      | 1.0  |           | 770 (3.751)         |
|                     | 2.0  |           | 11165 (54.389)      |
|                     | None |           | 8593 (41.860)       |
| M011071, n (%)      | 1.0  |           | 1335 (6.503)        |
|                     | 2.0  |           | 10600 (51.637)      |
|                     | None |           | 8593 (41.860)       |
| N004, n (%)         | 1.0  |           | 2822 (13.747)       |
|                     | 2.0  |           | 17358 (84.558)      |
|                     | None |           | 348 (1.695)         |
| N005, n (%)         | 1.0  |           | 1105 (5.383)        |
|                     | 2.0  |           | 19075 (92.922)      |
|                     | None |           | 348 (1.695)         |
| N008, n (%)         | 1.0  |           | 2226 (10.844)       |
|                     | 2.0  |           | 418 (2.036)         |
|                     | 3.0  |           | 199 (0.969)         |
|                     | 4.0  |           | 42 (0.205)          |
|                     | None |           | 17643 (85.946)      |
| N010, n (%)         | 1.0  |           | 12198 (59.421)      |
|                     | 2.0  |           | 3976 (19.369)       |
|                     | 3.0  |           | 1504 (7.327)        |
|                     | 4.0  |           | 2850 (13.883)       |
| N011, n (%)         | 1.0  |           | 12468 (60.737)      |
|                     | 2.0  |           | 4920 (23.967)       |
|                     | 3.0  |           | 1395 (6.796)        |
|                     | 4.0  |           | 1745 (8.501)        |
| N012, n (%)         | 1.0  |           | 14508 (70.674)      |
|                     | 2.0  |           | 4030 (19.632)       |
|                     | 3.0  |           | 940 (4.579)         |
|                     | 4.0  |           | 1050 (5.115)        |
| N016, n (%)         | 1.0  |           | 14544 (70.850)      |
|                     | 2.0  |           | 3868 (18.843)       |
|                     | 3.0  |           | 1013 (4.935)        |
|                     | 4.0  |           | 1103 (5.373)        |
| P00104, mean (SD)   |      | 27        | 71.788 (14.530)     |
| P00404, mean (SD)   |      | 27        | 163.353 (9.253)     |
| P00901, mean (SD)   |      | 0         | 4.281 (2.489)       |
| P01101, mean (SD)   |      | 0         | 3.151 (2.108)       |
| P02001, mean (SD)   |      | 0         | 0.791 (1.729)       |
| P018, mean (SD)     |      | 0         | 4.196 (2.495)       |
| P02002, mean (SD)   |      | 0         | 0.791 (1.484)       |
| P02501, mean (SD)   |      | 0         | 1.230 (1.948)       |
| P02602, mean (SD)   |      | 0         | 0.240 (0.866)       |
| P02601, n (%)       | 1.0  |           | 173 (0.843)         |
|                     | 2.0  |           | 1502 (7.317)        |
|                     | 3.0  |           | 11251 (54.808)      |
|                     | 4.0  |           | 6555 (31.932)       |
|                     | 5.0  |           | 1047 (5.100)        |
| P027, n (%)         | 1.0  |           | 13219 (64.395)      |
|                     | 2.0  |           | 2411 (11.745)       |
|                     | 3.0  |           | 4898 (23.860)       |
| P02801, mean (SD)   |      | 15630     | 1.847 (1.732)       |
| P029, mean (SD)     |      | 13219     | 4.850 (4.553)       |
| P035, mean (SD)     |      | 13136     | 3.648 (1.868)       |
| P03701, mean (SD)   |      | 13326     | 0.830 (0.733)       |
| P03702, mean (SD)   |      | 13326     | 15.352 (17.321)     |
| P04501, n (%)       | 1.0  |           | 4132 (20.129)       |
|                     | 2.0  |           | 6027 (29.360)       |
|                     | 3.0  |           | 4417 (21.517)       |
|                     | 4.0  |           | 3132 (15.257)       |
|                     | 5.0  |           | 1137 (5.539)        |
|                     | 6.0  |           | 1683 (8.199)        |
| P04502, n (%)       | 1.0  |           | 4216 (20.538)       |
|                     | 2.0  |           | 3340 (16.270)       |
|                     | 3.0  |           | 1886 (9.187)        |
|                     | 4.0  |           | 1397 (6.805)        |
|                     | 5.0  |           | 693 (3.376)         |
|                     | 6.0  |           | 8996 (43.823)       |
| P050, n (%)         | 1.0  |           | 2637 (12.846)       |
|                     | 2.0  |           | 225 (1.096)         |
|                     | 3.0  |           | 17666 (86.058)      |
| P051, n (%)         | 1.0  |           | 138 (0.672)         |
|                     | 2.0  |           | 87 (0.424)          |
|                     | None |           | 20303 (98.904)      |
| P052, n (%)         | 1.0  |           | 5652 (27.533)       |
|                     | 2.0  |           | 749 (3.649)         |
|                     | 3.0  |           | 11265 (54.876)      |
|                     | None |           | 2862 (13.942)       |
| P053, mean (SD)     |      | 12101     | 16.590 (6.409)      |
| P05401, n (%)       | 1.0  |           | 1644 (8.009)        |
|                     | 2.0  |           | 160 (0.779)         |
|                     | 3.0  |           | 80 (0.390)          |
|                     | 4.0  |           | 43 (0.209)          |
|                     | 5.0  |           | 935 (4.555)         |
|                     | None |           | 17666 (86.058)      |
| P05404, n (%)       | 1.0  |           | 1151 (5.607)        |
|                     | 2.0  |           | 79 (0.385)          |
|                     | 3.0  |           | 24 (0.117)          |
|                     | 4.0  |           | 24 (0.117)          |
|                     | 5.0  |           | 1584 (7.716)        |
|                     | None |           | 17666 (86.058)      |
| P05407, n (%)       | 1.0  |           | 4 (0.019)           |
|                     | 2.0  |           | 2 (0.010)           |
|                     | 3.0  |           | 4 (0.019)           |
|                     | 4.0  |           | 4 (0.019)           |
|                     | 5.0  |           | 2848 (13.874)       |
|                     | None |           | 17666 (86.058)      |
| P05410, n (%)       | 1.0  |           | 24 (0.117)          |
|                     | 2.0  |           | 6 (0.029)           |
|                     | 3.0  |           | 4 (0.019)           |
|                     | 4.0  |           | 3 (0.015)           |
|                     | 5.0  |           | 2825 (13.762)       |
|                     | None |           | 17666 (86.058)      |
| P05413, n (%)       | 1.0  |           | 4 (0.019)           |
|                     | 3.0  |           | 4 (0.019)           |
|                     | 4.0  |           | 3 (0.015)           |
|                     | 5.0  |           | 2851 (13.888)       |
|                     | None |           | 17666 (86.058)      |
| P05416, n (%)       | 2.0  |           | 1 (0.005)           |
|                     | 3.0  |           | 1 (0.005)           |
|                     | 4.0  |           | 4 (0.019)           |
|                     | 5.0  |           | 2856 (13.913)       |
|                     | None |           | 17666 (86.058)      |
| P05419, n (%)       | 1.0  |           | 6 (0.029)           |
|                     | 2.0  |           | 1 (0.005)           |
|                     | 5.0  |           | 2855 (13.908)       |
|                     | None |           | 17666 (86.058)      |
| P06701, n (%)       | 1.0  |           | 3 (0.015)           |
|                     | 2.0  |           | 4 (0.019)           |
|                     | 3.0  |           | 20 (0.097)          |
|                     | 4.0  |           | 20501 (99.868)      |
| P068, n (%)         | 1.0  |           | 2661 (12.963)       |
|                     | 2.0  |           | 355 (1.729)         |
|                     | 3.0  |           | 119 (0.580)         |
|                     | 4.0  |           | 308 (1.500)         |
|                     | 5.0  |           | 17085 (83.228)      |
| Q00201, n (%)       | 1.0  |           | 6996 (34.080)       |
|                     | 2.0  |           | 13337 (64.970)      |
|                     | None |           | 195 (0.950)         |
| Q03001, n (%)       | 1.0  |           | 2197 (10.702)       |
|                     | 2.0  |           | 17159 (83.588)      |
|                     | None |           | 1172 (5.709)        |
| Q060, n (%)         | 1.0  |           | 4191 (20.416)       |
|                     | 2.0  |           | 14916 (72.662)      |
|                     | None |           | 1421 (6.922)        |
| Q06306, n (%)       | 1.0  |           | 1154 (5.622)        |
|                     | 2.0  |           | 19374 (94.378)      |
| Q068, n (%)         | 1.0  |           | 521 (2.538)         |
|                     | 2.0  |           | 20007 (97.462)      |
| Q11006, n (%)       | 1.0  |           | 1105 (5.383)        |
|                     | 2.0  |           | 19423 (94.617)      |
| Q128, n (%)         | 1.0  |           | 1895 (9.231)        |
|                     | 2.0  |           | 18633 (90.769)      |
| R034, n (%)         | 1.0  |           | 1147 (5.587)        |
|                     | 2.0  |           | 1723 (8.393)        |
|                     | None |           | 17658 (86.019)      |
| T001, n (%)         | 1.0  |           | 709 (3.454)         |
|                     | 2.0  |           | 19819 (96.546)      |
| H003, n (%)         | 1.0  |           | 129 (0.628)         |
|                     | 2.0  |           | 1907 (9.290)        |
|                     | 3.0  |           | 15 (0.073)          |
|                     | 4.0  |           | 2694 (13.124)       |
|                     | 5.0  |           | 91 (0.443)          |
|                     | 6.0  |           | 124 (0.604)         |
|                     | 7.0  |           | 1432 (6.976)        |
|                     | 8.0  |           | 6 (0.029)           |
|                     | None |           | 14130 (68.833)      |
| H004, n (%)         | 1.0  |           | 2499 (12.174)       |
|                     | 10.0 |           | 87 (0.424)          |
|                     | 11.0 |           | 24 (0.117)          |
|                     | 12.0 |           | 42 (0.205)          |
|                     | 13.0 |           | 27 (0.132)          |
|                     | 2.0  |           | 199 (0.969)         |
|                     | 3.0  |           | 49 (0.239)          |
|                     | 4.0  |           | 163 (0.794)         |
|                     | 5.0  |           | 18 (0.088)          |
|                     | 6.0  |           | 74 (0.360)          |
|                     | 7.0  |           | 748 (3.644)         |
|                     | 8.0  |           | 2419 (11.784)       |
|                     | 9.0  |           | 49 (0.239)          |
|                     | None |           | 14130 (68.833)      |
| H010, n (%)         | 1.0  |           | 775 (3.775)         |
|                     | 2.0  |           | 573 (2.791)         |
|                     | 3.0  |           | 515 (2.509)         |
|                     | 4.0  |           | 615 (2.996)         |
|                     | 5.0  |           | 21 (0.102)          |
|                     | None |           | 18029 (87.826)      |
| D00201, n (%)       | 1.0  |           | 641 (3.123)         |
|                     | 2.0  |           | 19887 (96.877)      |
| D00301, n (%)       | 10.0 |           | 19 (0.093)          |
|                     | 11.0 |           | 8 (0.039)           |

In [42]:
#tem que acrescentar mínimo e máximo, eu não sei fazer isso ainda
for i in continuous:
    print("{i}, mean (SD / min / max) {l}")

{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}