In [1]:
# Import numerical libraries
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from tableone import TableOne

In [6]:
data = pd.read_csv('..\Bases\Criados\\base_doencas_cardiacas.csv')

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\llays\AppData\Local\Temp\ipykernel_14408\820377438.py:1: SyntaxWarning: invalid escape sequence '\B'
  data = pd.read_csv('..\Bases\Criados\\base_doencas_cardiacas.csv')

In [ ]:
categorical = ['V0001', 'V0015', 'V0026', 'V0031', 'B001', 'C006', 'C009', 'C011', 'C012', 'D00201', 'D008', 'D00901', 'D01301', 'D01303', 'D014', 'D015', 'E001', 'E002', 'E003', 'E004', 'E005', 'E006011', 
               'E008', 'E010010', 'E011', 'E014011', 'E01601', 'E01603', 'E01605', 'E01801', 'E027', 'F001011', 'F007011', 'F008011', 'VDF001', 'F016', 'G059', 'G060', 'G062', 'G032', 
               'I00102', 'I00103', 'I001031', 'C00301', 'I006', 'I004', 'I00401', 'I00402', 'I00403', 'I012', 'J001', 'J00101', 'J002', 'J00402', 'J00404', 'J007', 
               'J00801', 'J01101', 'J060', 'M001', 'M00203', 'M00302', 'M011011', 'M011021', 'M011051', 'M011071', 'N00101', 'N004', 'N005', 
               'N008', 'N010', 'N011', 'N012', 'N016', 'P02601', 'P027', 'P034', 'P050', 'P051', 'P052', 'P06701', 'P068', 'Q00101', 'Q00201', 'Q02901', 'Q03001', 'Q05901', 'Q060',
               'Q06306', 'Q06307', 'Q06308', 'Q06309', 'Q06310', 'Q06311', 'Q06506', 'Q06507', 'Q06508', 'Q06509', 'Q06601', 'Q067', 'Q068', 'Q11006', 
               'R010','R025', 'R028', 'R029', 'R030', 'R031', 'R032', 'R033', 'R034', 'R03601', 'R03607',
               'R03608', 'R03610', 'S065', 'T001', 'H001', 'H002', 'H003', 'H004', 'H010']

continuous = ['C008', 'E01602', 'E01604', 'E017', 'E01802', 'E01804', 'E019', 'P00103', 'P00104', 'P00403',
           'P00404', 'P00901', 'P01101', 'P02001', 'P018', 'P02002', 'P02501', 'P02602',
           'P02801', 'P029', 'P035', 'P03701', 'P03702', 'P04501', 'P04502', 'P053', 'P05401', 'P05404',
           'P05407', 'P05410', 'P05413', 'P05416', 'P05419', 'Q064']

In [ ]:
# Crie uma Tabela 1 simples sem nenhuma variável de agrupamento
# Teste de normalidade, multimodalidade (Teste de Mergulho de Hartigan) e valores discrepantes (teste de Tukey)

mytable = TableOne(data, categorical=categorical, continuous=continuous, dip_test=False, normal_test=False, tukey_test=False, decimals=3, include_null=True)

c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 10.0 10.0 ... 10.0 10.0 11.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 3.0 ... 3.0 3.0 3.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 1.0 ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 2.0 ... 'None' 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 3.0 ... 'None' 'None' 4.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 1.0 2.0 ... 1.0 'None' 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 2.0 ... 1.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 2.0 ... 2.0 1.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 3.0 2.0 ... 'None' 'None' 3.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 1.0 1.0 ... 2.0 'None' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)
c:\Users\bkser\AppData\Local\Programs\Python\Python313\Lib\site-packages\tableone\preprocessors.py:123: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['None' 'None' 'None' ... 'None' 'None' 'None']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(null_value)

In [ ]:
# View Table 1 (note the remarks below the table)
mytable

                       Missing              Overall
n                                             24392
V0001, n (%)      21                  2679 (10.983)
                  22                   1622 (6.650)
                  23                  2440 (10.003)
                  24                   1725 (7.072)
                  25                   1876 (7.691)
                  26                   2410 (9.880)
                  27                   1699 (6.965)
                  28                   1562 (6.404)
                  29                   2238 (9.175)
                  50                   1719 (7.047)
                  51                   1445 (5.924)
                  52                   1700 (6.969)
                  53                   1277 (5.235)
V0015, n (%)      1                 24392 (100.000)
V0026, n (%)      1                  17800 (72.975)
                  2                   6592 (27.025)
V0031, n (%)      1                   8852 (36.291)
                  2                   2694 (11.045)
                  3                     318 (1.304)
                  4                  12528 (51.361)
B001, n (%)       1.0                16707 (68.494)
                  2.0                 5140 (21.072)
                  3.0                 2545 (10.434)
C006, n (%)       1.0                11117 (45.576)
                  2.0                13275 (54.424)
C008, mean (SD)              0      57.340 (12.026)
C009, n (%)       1.0                 7254 (29.739)
                  2.0                 3055 (12.525)
                  3.0                   164 (0.672)
                  4.0                13724 (56.264)
                  5.0                   193 (0.791)
                  9.0                     2 (0.008)
C011, n (%)       1.0                10751 (44.076)
                  2.0                 2604 (10.676)
                  3.0                 3134 (12.848)
                  4.0                 7903 (32.400)
C012, n (%)       1.0                18693 (76.636)
                  2.0                 5699 (23.364)
D00201, n (%)     1.0                   687 (2.816)
                  2.0                23705 (97.184)
D008, n (%)       1.0                20938 (85.840)
                  2.0                 2767 (11.344)
                  None                  687 (2.816)
D00901, n (%)     1.0                     9 (0.037)
                  10.0                4552 (18.662)
                  11.0                  302 (1.238)
                  12.0                 2125 (8.712)
                  13.0                  780 (3.198)
                  14.0                  137 (0.562)
                  15.0                   57 (0.234)
                  2.0                   147 (0.603)
                  3.0                  1224 (5.018)
                  4.0                   332 (1.361)
                  5.0                 3931 (16.116)
                  6.0                   727 (2.980)
                  7.0                 5645 (23.143)
                  8.0                   436 (1.787)
                  9.0                   534 (2.189)
                  None                3454 (14.160)
D01301, n (%)     1.0                  1425 (5.842)
                  10.0                  374 (1.533)
                  11.0                    6 (0.025)
                  12.0                   29 (0.119)
                  2.0                  1600 (6.560)
                  3.0                 5538 (22.704)
                  4.0                 3460 (14.185)
                  5.0                  1462 (5.994)
                  6.0                   853 (3.497)
                  7.0                   604 (2.476)
                  8.0                  2007 (8.228)
                  9.0                    64 (0.262)
                  None                6970 (28.575)
D01303, n (%)     1.0                    12 (0.049)
                  2.0                    16 (0.066)
                  None               24364 (99.885)
D014, n (%)       1.0                 9719 (39.845)
                  2.0                10232 (41.948)
                  None                4441 (18.207)
D015, n (%)       1.0                18729 (76.783)
                  2.0                 5663 (23.217)
E001, n (%)       1.0                11109 (45.544)
                  2.0                13283 (54.456)
E002, n (%)       1.0                    73 (0.299)
                  2.0                13210 (54.157)
                  None               11109 (45.544)
E003, n (%)       1.0                   756 (3.099)
                  2.0                12454 (51.058)
                  None               11182 (45.843)
E004, n (%)       1.0                   144 (0.590)
                  2.0                12310 (50.467)
                  None               11938 (48.942)
E005, n (%)       1.0                   329 (1.349)
                  2.0                11981 (49.119)
                  None               12082 (49.533)
E006011, n (%)    1.0                   130 (0.533)
                  2.0                     5 (0.020)
                  3.0                   109 (0.447)
                  4.0                    13 (0.053)
                  5.0                    45 (0.184)
                  6.0                    10 (0.041)
                  7.0                    17 (0.070)
                  None               24063 (98.651)
E008, n (%)       1.0                    46 (0.189)
                  2.0                    63 (0.258)
                  None               24283 (99.553)
E010010, n (%)    1.0                    18 (0.074)
                  2.0                    31 (0.127)
                  3.0                    11 (0.045)
                  4.0                    12 (0.049)
                  None               24320 (99.705)
E011, n (%)       1.0                11634 (47.696)
                  2.0                   655 (2.685)
                  3.0                    85 (0.348)
                  None               12018 (49.270)
E014011, n (%)    1.0                   134 (0.549)
                  2.0                    11 (0.045)
                  None               24247 (99.406)
E01601, n (%)     1.0                12143 (49.783)
                  None               12249 (50.217)
E01603, n (%)     2.0                   152 (0.623)
                  None               24240 (99.377)
E01605, n (%)     1.0                     3 (0.012)
                  3.0                     1 (0.004)
                  None               24388 (99.984)
E01602, mean (SD)        12249  2084.110 (3608.799)
E01604, mean (SD)        24240    377.441 (628.429)
E017, mean (SD)          12018      36.144 (13.988)
E01801, n (%)     1.0                   723 (2.964)
                  None               23669 (97.036)
E01802, mean (SD)        23669  1629.538 (2421.323)
E01804, mean (SD)        24373    154.789 (153.700)
E019, mean (SD)          23652      17.988 (10.881)
E027, n (%)       1.0                18674 (76.558)
                  2.0                 5718 (23.442)
F001011, n (%)    1.0                 9219 (37.795)
                  2.0                15173 (62.205)
F007011, n (%)    1.0                   758 (3.108)
                  2.0                23634 (96.892)
F008011, n (%)    1.0                  1142 (4.682)
                  2.0                23250 (95.318)
VDF001, n (%)     1.0                 3479 (14.263)
                  2.0                20913 (85.737)
F016, n (%)       1.0                18690 (76.623)
                  2.0                 5702 (23.377)
G059, n (%)       1.0                   736 (3.017)
                  2.0                23656 (96.983)
G060, n (%)       1.0                   154 (0.631)
                  2.0                   582 (2.386)
                  None               23656 (96.983)
G062, n (%)       1.0                   576 (2.361)
                  2.0                   160 (0.656)
                  None               23656 (96.983)
G032, n (%)       1.0                18699 (76.660)
                  2.0                 5693 (23.340)
I00102, n (%)     1.0                 4608 (18.891)
                  2.0                19784 (81.109)
I00103, n (%)     1.0                 4380 (17.957)
                  2.0                   228 (0.935)
                  None               19784 (81.109)
I001031, n (%)    1.0                 3168 (12.988)
                  2.0                  1100 (4.510)
                  3.0                    83 (0.340)
                  4.0                    22 (0.090)
                  5.0                     4 (0.016)
                  6.0                     3 (0.012)
                  None               20012 (82.043)
C00301, n (%)     1.0                18499 (75.840)
                  2.0                 5131 (21.036)
                  3.0                   507 (2.079)
                  4.0                   153 (0.627)
                  5.0                    67 (0.275)
                  6.0                    21 (0.086)
                  7.0                    11 (0.045)
                  8.0                     3 (0.012)
I006, n (%)       1.0                  1020 (4.182)
                  2.0                  2394 (9.815)
                  3.0                   941 (3.858)
                  4.0                   108 (0.443)
                  5.0                    49 (0.201)
                  6.0                    96 (0.394)
                  None               19784 (81.109)
I004, n (%)       1.0                  1327 (5.440)
                  2.0                  2158 (8.847)
                  None               20907 (85.713)
I00401, n (%)     1.0                 3441 (14.107)
                  2.0                    44 (0.180)
                  None               20907 (85.713)
I00402, n (%)     1.0                 3425 (14.041)
                  2.0                    60 (0.246)
                  None               20907 (85.713)
I00403, n (%)     1.0                 3284 (13.463)
                  2.0                   201 (0.824)
                  None               20907 (85.713)
I012, n (%)       1.0                18680 (76.582)
                  2.0                 5708 (23.401)
                  None                    4 (0.016)
J001, n (%)       1.0                  1944 (7.970)
                  2.0                 9948 (40.784)
                  3.0                 9799 (40.173)
                  4.0                  2195 (8.999)
                  5.0                   506 (2.074)
J00101, n (%)     1.0                 2656 (10.889)
                  2.0                13110 (53.747)
                  3.0                 6947 (28.481)
                  4.0                  1422 (5.830)
                  5.0                   257 (1.054)
J002, n (%)       1.0                 2887 (11.836)
                  2.0                21505 (88.164)
J00402, n (%)     1.0                  1139 (4.670)
                  10.0                   51 (0.209)
                  11.0                   42 (0.172)
                  12.0                  143 (0.586)
                  13.0                  159 (0.652)
                  14.0                  226 (0.927)
                  2.0                   182 (0.746)
                  3.0                    30 (0.123)
                  4.0                    30 (0.123)
                  5.0                   303 (1.242)
                  6.0                   181 (0.742)
                  7.0                    67 (0.275)
                  8.0                   265 (1.086)
                  9.0                    69 (0.283)
                  None               21505 (88.164)
J00404, n (%)     1.0                   481 (1.972)
                  2.0                  2131 (8.736)
                  3.0                   275 (1.127)
                  None               21505 (88.164)
J007, n (%)       1.0                16033 (65.731)
                  2.0                 8359 (34.269)
J00801, n (%)     1.0                 9191 (37.680)
                  2.0                 6842 (28.050)
                  None                8359 (34.269)
J01101, n (%)     1.0                19642 (80.526)
                  2.0                  2218 (9.093)
                  3.0                   747 (3.062)
                  4.0                  1630 (6.683)
                  5.0                   155 (0.635)
J060, n (%)       1.0                18776 (76.976)
                  2.0                 5616 (23.024)
M001, n (%)       1.0               24392 (100.000)
M00203, n (%)     1.0                23986 (98.336)
                  2.0                   400 (1.640)
                  9.0                     3 (0.012)
                  None                    3 (0.012)
M00302, n (%)     1.0                   401 (1.644)
                  None               23991 (98.356)
M011011, n (%)    1.0                  1417 (5.809)
                  2.0                10957 (44.920)
                  None               12018 (49.270)
M011021, n (%)    1.0                  2262 (9.274)
                  2.0                10112 (41.456)
                  None               12018 (49.270)
M011051, n (%)    1.0                   780 (3.198)
                  2.0                11594 (47.532)
                  None               12018 (49.270)
M011071, n (%)    1.0                  1366 (5.600)
                  2.0                11008 (45.130)
                  None               12018 (49.270)
N00101, n (%)     1.0                 2609 (10.696)
                  2.0                12969 (53.169)
                  3.0                 7107 (29.137)
                  4.0                  1439 (5.899)
                  5.0                   268 (1.099)
N004, n (%)       1.0                 3278 (13.439)
                  2.0                20378 (83.544)
                  None                  736 (3.017)
N005, n (%)       1.0                  1307 (5.358)
                  2.0                22349 (91.624)
                  None                  736 (3.017)
N008, n (%)       1.0                 2576 (10.561)
                  2.0                   515 (2.111)
                  3.0                   220 (0.902)
                  4.0                    49 (0.201)
                  None               21032 (86.225)
N010, n (%)       1.0                14386 (58.978)
                  2.0                 4701 (19.273)
                  3.0                  1804 (7.396)
                  4.0                 3501 (14.353)
N011, n (%)       1.0                15017 (61.565)
                  2.0                 5753 (23.586)
                  3.0                  1621 (6.646)
                  4.0                  2001 (8.204)
N012, n (%)       1.0                17427 (71.446)
                  2.0                 4653 (19.076)
                  3.0                  1090 (4.469)
                  4.0                  1222 (5.010)
N016, n (%)       1.0                17420 (71.417)
                  2.0                 4503 (18.461)
                  3.0                  1184 (4.854)
                  4.0                  1285 (5.268)
P00103, mean (SD)         2196      71.010 (14.556)
P00104, mean (SD)           27      70.812 (14.433)
P00403, mean (SD)         5632      163.614 (9.409)
P00404, mean (SD)           27      162.873 (9.309)
P00901, mean (SD)            0        4.267 (2.500)
P01101, mean (SD)            0        3.140 (2.125)
P02001, mean (SD)            0        0.777 (1.716)
P018, mean (SD)              0        4.266 (2.488)
P02002, mean (SD)            0        0.747 (1.456)
P02501, mean (SD)            0        1.226 (1.966)
P02602, mean (SD)            0        0.226 (0.858)
P02601, n (%)     1.0                   192 (0.787)
                  2.0                  1661 (6.810)
                  3.0                12994 (53.272)
                  4.0                 8171 (33.499)
                  5.0                  1374 (5.633)
P027, n (%)       1.0                16518 (67.719)
                  2.0                 2655 (10.885)
                  3.0                 5219 (21.396)
P02801, mean (SD)        19173        1.877 (1.784)
P029, mean (SD)          16518        4.713 (4.475)
P034, n (%)       1.0                 8274 (33.921)
                  2.0                16118 (66.079)
P035, mean (SD)          16118        3.684 (1.881)
P03701, mean (SD)        16327        0.802 (0.739)
P03702, mean (SD)        16327      15.666 (17.299)
P04501, mean (SD)            0        2.865 (1.489)
P04502, mean (SD)            0        4.090 (2.091)
P050, n (%)       1.0                 2997 (12.287)
                  2.0                   240 (0.984)
                  3.0                21155 (86.729)
P051, n (%)       1.0                   149 (0.611)
                  2.0                    91 (0.373)
                  None               24152 (99.016)
P052, n (%)       1.0                 7218 (29.592)
                  2.0                   895 (3.669)
                  3.0                13042 (53.468)
                  None                3237 (13.271)
P053, mean (SD)          14028       16.607 (6.912)
P05401, mean (SD)        21155        2.571 (1.874)
P05404, mean (SD)        21155        3.220 (1.953)
P05407, mean (SD)        21155        4.989 (0.177)
P05410, mean (SD)        21155        4.906 (0.593)
P05413, mean (SD)        21155        4.990 (0.175)
P05416, mean (SD)        21155        4.997 (0.072)
P05419, mean (SD)        21155        4.988 (0.215)
P06701, n (%)     1.0                     3 (0.012)
                  2.0                     4 (0.016)
                  3.0                    25 (0.102)
                  4.0                24360 (99.869)
P068, n (%)       1.0                 3101 (12.713)
                  2.0                   401 (1.644)
                  3.0                   146 (0.599)
                  4.0                   369 (1.513)
                  5.0                20375 (83.531)
Q00201, n (%)     1.0                 9359 (38.369)
                  2.0                14817 (60.745)
                  None                  216 (0.886)
Q03001, n (%)     1.0                 2983 (12.229)
                  2.0                20113 (82.457)
                  None                 1296 (5.313)
Q060, n (%)       1.0                 5158 (21.146)
                  2.0                17650 (72.360)
                  None                 1584 (6.494)
Q06306, n (%)     1.0                  1669 (6.842)
                  2.0                22723 (93.158)
Q064, mean (SD)          22723      51.575 (17.102)
Q06506, n (%)     1.0                   892 (3.657)
                  2.0                   777 (3.185)
                  None               22723 (93.158)
Q06507, n (%)     1.0                   547 (2.243)
                  2.0                  1122 (4.600)
                  None               22723 (93.158)
Q06508, n (%)     1.0                  1255 (5.145)
                  2.0                   414 (1.697)
                  None               22723 (93.158)
Q06509, n (%)     1.0                  1147 (4.702)
                  2.0                   522 (2.140)
                  None               22723 (93.158)
Q06601, n (%)     1.0                   544 (2.230)
                  2.0                  1125 (4.612)
                  None               22723 (93.158)
Q067, n (%)       1.0                   775 (3.177)
                  2.0                   422 (1.730)
                  3.0                   265 (1.086)
                  4.0                   155 (0.635)
                  5.0                    52 (0.213)
                  None               22723 (93.158)
Q068, n (%)       1.0                   809 (3.317)
                  2.0                23583 (96.683)
Q11006, n (%)     1.0                  1204 (4.936)
                  2.0                23188 (95.064)

In [ ]:
print(mytable.tabulate(tablefmt="github"))

|                   |      | Missing   | Overall             |
|-------------------|------|-----------|---------------------|
| n                 |      |           | 24392               |
| V0001, n (%)      | 21   |           | 2679 (10.983)       |
|                   | 22   |           | 1622 (6.650)        |
|                   | 23   |           | 2440 (10.003)       |
|                   | 24   |           | 1725 (7.072)        |
|                   | 25   |           | 1876 (7.691)        |
|                   | 26   |           | 2410 (9.880)        |
|                   | 27   |           | 1699 (6.965)        |
|                   | 28   |           | 1562 (6.404)        |
|                   | 29   |           | 2238 (9.175)        |
|                   | 50   |           | 1719 (7.047)        |
|                   | 51   |           | 1445 (5.924)        |
|                   | 52   |           | 1700 (6.969)        |
|                   | 53   |           | 1277 (5.235)        |
| V0015, n (%)      | 1    |           | 24392 (100.000)     |
| V0026, n (%)      | 1    |           | 17800 (72.975)      |
|                   | 2    |           | 6592 (27.025)       |
| V0031, n (%)      | 1    |           | 8852 (36.291)       |
|                   | 2    |           | 2694 (11.045)       |
|                   | 3    |           | 318 (1.304)         |
|                   | 4    |           | 12528 (51.361)      |
| B001, n (%)       | 1.0  |           | 16707 (68.494)      |
|                   | 2.0  |           | 5140 (21.072)       |
|                   | 3.0  |           | 2545 (10.434)       |
| C006, n (%)       | 1.0  |           | 11117 (45.576)      |
|                   | 2.0  |           | 13275 (54.424)      |
| C008, mean (SD)   |      | 0         | 57.340 (12.026)     |
| C009, n (%)       | 1.0  |           | 7254 (29.739)       |
|                   | 2.0  |           | 3055 (12.525)       |
|                   | 3.0  |           | 164 (0.672)         |
|                   | 4.0  |           | 13724 (56.264)      |
|                   | 5.0  |           | 193 (0.791)         |
|                   | 9.0  |           | 2 (0.008)           |
| C011, n (%)       | 1.0  |           | 10751 (44.076)      |
|                   | 2.0  |           | 2604 (10.676)       |
|                   | 3.0  |           | 3134 (12.848)       |
|                   | 4.0  |           | 7903 (32.400)       |
| C012, n (%)       | 1.0  |           | 18693 (76.636)      |
|                   | 2.0  |           | 5699 (23.364)       |
| D00201, n (%)     | 1.0  |           | 687 (2.816)         |
|                   | 2.0  |           | 23705 (97.184)      |
| D008, n (%)       | 1.0  |           | 20938 (85.840)      |
|                   | 2.0  |           | 2767 (11.344)       |
|                   | None |           | 687 (2.816)         |
| D00901, n (%)     | 1.0  |           | 9 (0.037)           |
|                   | 10.0 |           | 4552 (18.662)       |
|                   | 11.0 |           | 302 (1.238)         |
|                   | 12.0 |           | 2125 (8.712)        |
|                   | 13.0 |           | 780 (3.198)         |
|                   | 14.0 |           | 137 (0.562)         |
|                   | 15.0 |           | 57 (0.234)          |
|                   | 2.0  |           | 147 (0.603)         |
|                   | 3.0  |           | 1224 (5.018)        |
|                   | 4.0  |           | 332 (1.361)         |
|                   | 5.0  |           | 3931 (16.116)       |
|                   | 6.0  |           | 727 (2.980)         |
|                   | 7.0  |           | 5645 (23.143)       |
|                   | 8.0  |           | 436 (1.787)         |
|                   | 9.0  |           | 534 (2.189)         |
|                   | None |           | 3454 (14.160)       |
| D01301, n (%)     | 1.0  |           | 1425 (5.842)        |
|                   | 10.0 |           | 374 (1.533)         |
|                   | 11.0 |           | 6 (0.025)           |
|                   | 12.0 |           | 29 (0.119)          |
|                   | 2.0  |           | 1600 (6.560)        |
|                   | 3.0  |           | 5538 (22.704)       |
|                   | 4.0  |           | 3460 (14.185)       |
|                   | 5.0  |           | 1462 (5.994)        |
|                   | 6.0  |           | 853 (3.497)         |
|                   | 7.0  |           | 604 (2.476)         |
|                   | 8.0  |           | 2007 (8.228)        |
|                   | 9.0  |           | 64 (0.262)          |
|                   | None |           | 6970 (28.575)       |
| D01303, n (%)     | 1.0  |           | 12 (0.049)          |
|                   | 2.0  |           | 16 (0.066)          |
|                   | None |           | 24364 (99.885)      |
| D014, n (%)       | 1.0  |           | 9719 (39.845)       |
|                   | 2.0  |           | 10232 (41.948)      |
|                   | None |           | 4441 (18.207)       |
| D015, n (%)       | 1.0  |           | 18729 (76.783)      |
|                   | 2.0  |           | 5663 (23.217)       |
| E001, n (%)       | 1.0  |           | 11109 (45.544)      |
|                   | 2.0  |           | 13283 (54.456)      |
| E002, n (%)       | 1.0  |           | 73 (0.299)          |
|                   | 2.0  |           | 13210 (54.157)      |
|                   | None |           | 11109 (45.544)      |
| E003, n (%)       | 1.0  |           | 756 (3.099)         |
|                   | 2.0  |           | 12454 (51.058)      |
|                   | None |           | 11182 (45.843)      |
| E004, n (%)       | 1.0  |           | 144 (0.590)         |
|                   | 2.0  |           | 12310 (50.467)      |
|                   | None |           | 11938 (48.942)      |
| E005, n (%)       | 1.0  |           | 329 (1.349)         |
|                   | 2.0  |           | 11981 (49.119)      |
|                   | None |           | 12082 (49.533)      |
| E006011, n (%)    | 1.0  |           | 130 (0.533)         |
|                   | 2.0  |           | 5 (0.020)           |
|                   | 3.0  |           | 109 (0.447)         |
|                   | 4.0  |           | 13 (0.053)          |
|                   | 5.0  |           | 45 (0.184)          |
|                   | 6.0  |           | 10 (0.041)          |
|                   | 7.0  |           | 17 (0.070)          |
|                   | None |           | 24063 (98.651)      |
| E008, n (%)       | 1.0  |           | 46 (0.189)          |
|                   | 2.0  |           | 63 (0.258)          |
|                   | None |           | 24283 (99.553)      |
| E010010, n (%)    | 1.0  |           | 18 (0.074)          |
|                   | 2.0  |           | 31 (0.127)          |
|                   | 3.0  |           | 11 (0.045)          |
|                   | 4.0  |           | 12 (0.049)          |
|                   | None |           | 24320 (99.705)      |
| E011, n (%)       | 1.0  |           | 11634 (47.696)      |
|                   | 2.0  |           | 655 (2.685)         |
|                   | 3.0  |           | 85 (0.348)          |
|                   | None |           | 12018 (49.270)      |
| E014011, n (%)    | 1.0  |           | 134 (0.549)         |
|                   | 2.0  |           | 11 (0.045)          |
|                   | None |           | 24247 (99.406)      |
| E01601, n (%)     | 1.0  |           | 12143 (49.783)      |
|                   | None |           | 12249 (50.217)      |
| E01603, n (%)     | 2.0  |           | 152 (0.623)         |
|                   | None |           | 24240 (99.377)      |
| E01605, n (%)     | 1.0  |           | 3 (0.012)           |
|                   | 3.0  |           | 1 (0.004)           |
|                   | None |           | 24388 (99.984)      |
| E01602, mean (SD) |      | 12249     | 2084.110 (3608.799) |
| E01604, mean (SD) |      | 24240     | 377.441 (628.429)   |
| E017, mean (SD)   |      | 12018     | 36.144 (13.988)     |
| E01801, n (%)     | 1.0  |           | 723 (2.964)         |
|                   | None |           | 23669 (97.036)      |
| E01802, mean (SD) |      | 23669     | 1629.538 (2421.323) |
| E01804, mean (SD) |      | 24373     | 154.789 (153.700)   |
| E019, mean (SD)   |      | 23652     | 17.988 (10.881)     |
| E027, n (%)       | 1.0  |           | 18674 (76.558)      |
|                   | 2.0  |           | 5718 (23.442)       |
| F001011, n (%)    | 1.0  |           | 9219 (37.795)       |
|                   | 2.0  |           | 15173 (62.205)      |
| F007011, n (%)    | 1.0  |           | 758 (3.108)         |
|                   | 2.0  |           | 23634 (96.892)      |
| F008011, n (%)    | 1.0  |           | 1142 (4.682)        |
|                   | 2.0  |           | 23250 (95.318)      |
| VDF001, n (%)     | 1.0  |           | 3479 (14.263)       |
|                   | 2.0  |           | 20913 (85.737)      |
| F016, n (%)       | 1.0  |           | 18690 (76.623)      |
|                   | 2.0  |           | 5702 (23.377)       |
| G059, n (%)       | 1.0  |           | 736 (3.017)         |
|                   | 2.0  |           | 23656 (96.983)      |
| G060, n (%)       | 1.0  |           | 154 (0.631)         |
|                   | 2.0  |           | 582 (2.386)         |
|                   | None |           | 23656 (96.983)      |
| G062, n (%)       | 1.0  |           | 576 (2.361)         |
|                   | 2.0  |           | 160 (0.656)         |
|                   | None |           | 23656 (96.983)      |
| G032, n (%)       | 1.0  |           | 18699 (76.660)      |
|                   | 2.0  |           | 5693 (23.340)       |
| I00102, n (%)     | 1.0  |           | 4608 (18.891)       |
|                   | 2.0  |           | 19784 (81.109)      |
| I00103, n (%)     | 1.0  |           | 4380 (17.957)       |
|                   | 2.0  |           | 228 (0.935)         |
|                   | None |           | 19784 (81.109)      |
| I001031, n (%)    | 1.0  |           | 3168 (12.988)       |
|                   | 2.0  |           | 1100 (4.510)        |
|                   | 3.0  |           | 83 (0.340)          |
|                   | 4.0  |           | 22 (0.090)          |
|                   | 5.0  |           | 4 (0.016)           |
|                   | 6.0  |           | 3 (0.012)           |
|                   | None |           | 20012 (82.043)      |
| C00301, n (%)     | 1.0  |           | 18499 (75.840)      |
|                   | 2.0  |           | 5131 (21.036)       |
|                   | 3.0  |           | 507 (2.079)         |
|                   | 4.0  |           | 153 (0.627)         |
|                   | 5.0  |           | 67 (0.275)          |
|                   | 6.0  |           | 21 (0.086)          |
|                   | 7.0  |           | 11 (0.045)          |
|                   | 8.0  |           | 3 (0.012)           |
| I006, n (%)       | 1.0  |           | 1020 (4.182)        |
|                   | 2.0  |           | 2394 (9.815)        |
|                   | 3.0  |           | 941 (3.858)         |
|                   | 4.0  |           | 108 (0.443)         |
|                   | 5.0  |           | 49 (0.201)          |
|                   | 6.0  |           | 96 (0.394)          |
|                   | None |           | 19784 (81.109)      |
| I004, n (%)       | 1.0  |           | 1327 (5.440)        |
|                   | 2.0  |           | 2158 (8.847)        |
|                   | None |           | 20907 (85.713)      |
| I00401, n (%)     | 1.0  |           | 3441 (14.107)       |
|                   | 2.0  |           | 44 (0.180)          |
|                   | None |           | 20907 (85.713)      |
| I00402, n (%)     | 1.0  |           | 3425 (14.041)       |
|                   | 2.0  |           | 60 (0.246)          |
|                   | None |           | 20907 (85.713)      |
| I00403, n (%)     | 1.0  |           | 3284 (13.463)       |
|                   | 2.0  |           | 201 (0.824)         |
|                   | None |           | 20907 (85.713)      |
| I012, n (%)       | 1.0  |           | 18680 (76.582)      |
|                   | 2.0  |           | 5708 (23.401)       |
|                   | None |           | 4 (0.016)           |
| J001, n (%)       | 1.0  |           | 1944 (7.970)        |
|                   | 2.0  |           | 9948 (40.784)       |
|                   | 3.0  |           | 9799 (40.173)       |
|                   | 4.0  |           | 2195 (8.999)        |
|                   | 5.0  |           | 506 (2.074)         |
| J00101, n (%)     | 1.0  |           | 2656 (10.889)       |
|                   | 2.0  |           | 13110 (53.747)      |
|                   | 3.0  |           | 6947 (28.481)       |
|                   | 4.0  |           | 1422 (5.830)        |
|                   | 5.0  |           | 257 (1.054)         |
| J002, n (%)       | 1.0  |           | 2887 (11.836)       |
|                   | 2.0  |           | 21505 (88.164)      |
| J00402, n (%)     | 1.0  |           | 1139 (4.670)        |
|                   | 10.0 |           | 51 (0.209)          |
|                   | 11.0 |           | 42 (0.172)          |
|                   | 12.0 |           | 143 (0.586)         |
|                   | 13.0 |           | 159 (0.652)         |
|                   | 14.0 |           | 226 (0.927)         |
|                   | 2.0  |           | 182 (0.746)         |
|                   | 3.0  |           | 30 (0.123)          |
|                   | 4.0  |           | 30 (0.123)          |
|                   | 5.0  |           | 303 (1.242)         |
|                   | 6.0  |           | 181 (0.742)         |
|                   | 7.0  |           | 67 (0.275)          |
|                   | 8.0  |           | 265 (1.086)         |
|                   | 9.0  |           | 69 (0.283)          |
|                   | None |           | 21505 (88.164)      |
| J00404, n (%)     | 1.0  |           | 481 (1.972)         |
|                   | 2.0  |           | 2131 (8.736)        |
|                   | 3.0  |           | 275 (1.127)         |
|                   | None |           | 21505 (88.164)      |
| J007, n (%)       | 1.0  |           | 16033 (65.731)      |
|                   | 2.0  |           | 8359 (34.269)       |
| J00801, n (%)     | 1.0  |           | 9191 (37.680)       |
|                   | 2.0  |           | 6842 (28.050)       |
|                   | None |           | 8359 (34.269)       |
| J01101, n (%)     | 1.0  |           | 19642 (80.526)      |
|                   | 2.0  |           | 2218 (9.093)        |
|                   | 3.0  |           | 747 (3.062)         |
|                   | 4.0  |           | 1630 (6.683)        |
|                   | 5.0  |           | 155 (0.635)         |
| J060, n (%)       | 1.0  |           | 18776 (76.976)      |
|                   | 2.0  |           | 5616 (23.024)       |
| M001, n (%)       | 1.0  |           | 24392 (100.000)     |
| M00203, n (%)     | 1.0  |           | 23986 (98.336)      |
|                   | 2.0  |           | 400 (1.640)         |
|                   | 9.0  |           | 3 (0.012)           |
|                   | None |           | 3 (0.012)           |
| M00302, n (%)     | 1.0  |           | 401 (1.644)         |
|                   | None |           | 23991 (98.356)      |
| M011011, n (%)    | 1.0  |           | 1417 (5.809)        |
|                   | 2.0  |           | 10957 (44.920)      |
|                   | None |           | 12018 (49.270)      |
| M011021, n (%)    | 1.0  |           | 2262 (9.274)        |
|                   | 2.0  |           | 10112 (41.456)      |
|                   | None |           | 12018 (49.270)      |
| M011051, n (%)    | 1.0  |           | 780 (3.198)         |
|                   | 2.0  |           | 11594 (47.532)      |
|                   | None |           | 12018 (49.270)      |
| M011071, n (%)    | 1.0  |           | 1366 (5.600)        |
|                   | 2.0  |           | 11008 (45.130)      |
|                   | None |           | 12018 (49.270)      |
| N00101, n (%)     | 1.0  |           | 2609 (10.696)       |
|                   | 2.0  |           | 12969 (53.169)      |
|                   | 3.0  |           | 7107 (29.137)       |
|                   | 4.0  |           | 1439 (5.899)        |
|                   | 5.0  |           | 268 (1.099)         |
| N004, n (%)       | 1.0  |           | 3278 (13.439)       |
|                   | 2.0  |           | 20378 (83.544)      |
|                   | None |           | 736 (3.017)         |
| N005, n (%)       | 1.0  |           | 1307 (5.358)        |
|                   | 2.0  |           | 22349 (91.624)      |
|                   | None |           | 736 (3.017)         |
| N008, n (%)       | 1.0  |           | 2576 (10.561)       |
|                   | 2.0  |           | 515 (2.111)         |
|                   | 3.0  |           | 220 (0.902)         |
|                   | 4.0  |           | 49 (0.201)          |
|                   | None |           | 21032 (86.225)      |
| N010, n (%)       | 1.0  |           | 14386 (58.978)      |
|                   | 2.0  |           | 4701 (19.273)       |
|                   | 3.0  |           | 1804 (7.396)        |
|                   | 4.0  |           | 3501 (14.353)       |
| N011, n (%)       | 1.0  |           | 15017 (61.565)      |
|                   | 2.0  |           | 5753 (23.586)       |
|                   | 3.0  |           | 1621 (6.646)        |
|                   | 4.0  |           | 2001 (8.204)        |
| N012, n (%)       | 1.0  |           | 17427 (71.446)      |
|                   | 2.0  |           | 4653 (19.076)       |
|                   | 3.0  |           | 1090 (4.469)        |
|                   | 4.0  |           | 1222 (5.010)        |
| N016, n (%)       | 1.0  |           | 17420 (71.417)      |
|                   | 2.0  |           | 4503 (18.461)       |
|                   | 3.0  |           | 1184 (4.854)        |
|                   | 4.0  |           | 1285 (5.268)        |
| P00103, mean (SD) |      | 2196      | 71.010 (14.556)     |
| P00104, mean (SD) |      | 27        | 70.812 (14.433)     |
| P00403, mean (SD) |      | 5632      | 163.614 (9.409)     |
| P00404, mean (SD) |      | 27        | 162.873 (9.309)     |
| P00901, mean (SD) |      | 0         | 4.267 (2.500)       |
| P01101, mean (SD) |      | 0         | 3.140 (2.125)       |
| P02001, mean (SD) |      | 0         | 0.777 (1.716)       |
| P018, mean (SD)   |      | 0         | 4.266 (2.488)       |
| P02002, mean (SD) |      | 0         | 0.747 (1.456)       |
| P02501, mean (SD) |      | 0         | 1.226 (1.966)       |
| P02602, mean (SD) |      | 0         | 0.226 (0.858)       |
| P02601, n (%)     | 1.0  |           | 192 (0.787)         |
|                   | 2.0  |           | 1661 (6.810)        |
|                   | 3.0  |           | 12994 (53.272)      |
|                   | 4.0  |           | 8171 (33.499)       |
|                   | 5.0  |           | 1374 (5.633)        |
| P027, n (%)       | 1.0  |           | 16518 (67.719)      |
|                   | 2.0  |           | 2655 (10.885)       |
|                   | 3.0  |           | 5219 (21.396)       |
| P02801, mean (SD) |      | 19173     | 1.877 (1.784)       |
| P029, mean (SD)   |      | 16518     | 4.713 (4.475)       |
| P034, n (%)       | 1.0  |           | 8274 (33.921)       |
|                   | 2.0  |           | 16118 (66.079)      |
| P035, mean (SD)   |      | 16118     | 3.684 (1.881)       |

In [ ]:
#tem que acrescentar mínimo e máximo eu não sei fazer isso ainda
for i in continuous:
    print("{i}, mean (SD / min / max) {l}")

{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}
{i}, mean (SD / min / max) {l}